import "./globals.css";
import { Sora } from "next/font/google";
import Navebar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Wrapper from "@/components/Wrapper";

const inter = Sora({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Heckathon-one",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={`${inter.className} overflow-x-hidden`}>
          <Wrapper>
            <Navebar />
            <main className="px-10 lg:px-20">{children}</main>
            <Footer />
          </Wrapper>
        </body>
    </html>
  );
}
