import { Product } from "./types";
import fp1 from "/public/images/fp1.png";
import { NavbarItemsType } from "./NavebarArrayAndTypes";

export const products = [
  {
    id: 1,
    name: "Brushed Raglan Sweatshirt",
    price: 195,
    description: "Sweater",
    category: "female",
    image: fp1,
  },
  {
    id: 2,
    name: "Cameryn Sash Tie Dress",
    price: 545,
    description: "Dress",
    category: "female",
    image: fp1,
  },
  {
    id: 3,
    name: "Flex Sweatshirt",
    price: 175,
    description: "Sweater",
    category: "female",
    image: fp1,
  },
  {
    id: 4,
    name: "Flex Sweatpants",
    price: 175,
    description: "Pants",
    category: "female",
    image: fp1,
  },
  {
    id: 5,
    name: "Brushed Raglan Sweatshirt",
    price: 195,
    description: "Pants",
    category: "female",
    image: fp1,
  },
  {
    id: 6,
    name: "Lite Sweatpants",
    price: 150,
    description: "Pants",
    category: "female",
    image: fp1,
  },
  {
    id: 7,
    name: "Imperial Alpaca Hoodie",
    price: 525,
    description: "Jackets",
    category: "female",
    image: fp1,
  },
  {
    id: 8,
    name: "Flex Push Button Bomber",
    price: 225,
    description: "Jackets",
    category: "male",
    image: fp1,
  },
  {
    id: 9,
    name: "Muscle Tank",
    price: 75,
    description: "T-shirt",
    category: "female",
    image: fp1,
  },
  {
    id: 10,
    name: "Brushed Bomber",
    price: 225,
    description: "Jackets",
    category: "female",
    image: fp1,
  },
  {
    id: 11,
    name: "Raglan Sweatshirt",
    price: 195,
    description: "Sweater",
    category: "male",
    image: fp1,
  },
  {
    id: 12,
    name: "Cotton Romper Nana",
    price: 50,
    description: "Romper",
    category: "kids",
    image: fp1,
  },
  {
    id: 13,
    name: "Cotton Romper Rainbow",
    price: 55,
    description: "Romper",
    category: "kids",
    image: fp1,
  },
];
